export const GET_CLIENT_LIST = 'GET_CLIENT_LIST';
export const GETING_CLIENT_LIST_ERROR = 'GETING_CLIENT_LIST_ERROR';

export const CHOOSE_CLIENT = 'CHOOSE_CLIENT';
export const RESET_CHOOSED_CLIENT = 'RESET_CHOOSED_CLIENT';

export const SEARCH_CLIENT_BY = 'SEARCH_CLIENT_BY';

export const MAKE_FOCUSED = 'MAKE_FOCUSED';

export const GETING_LOADING = 'GETING_LOADING';

export const RESET_SEARCH = 'RESET_SEARCH';